### ISSUE TITLE
vectorial get_geocentric_angle

### ISSUE THREAD

**Issue by fgnievinski** [ufrgs-gnss-lab/geo-alhazen#27]
check equivalence:
$\theta=acos(\vec{R_s}/R_s\cdot\vec{R_a}/R_a)$

**Comment by vitorhjr** [comment]
I corrected the formula to `geo_ang = 2*acosd(temp)-90`. It is producing results with a precision of 10e-7 degrees for an antenna height of 100m as it's shown below. 
![image](https://user-images.githubusercontent.com/89110447/211410889-26d48e14-0fad-4cbb-bfb5-894d710fb723.png)

I only have difficulty computing the vectorial formula at zenith exactly. At zenith,  the code `acosd(temp)` sometimes results in 180° instead 90° because the Y coord. of specular points vary in positive and negative values. Although, the Y coord. is too much closer to zero (e.g. -10e-9 or +10e-9), this variation in sign is enough to cross the trigonometric circle from 90° to 180°.

Furthermore, there are cases at zenith in which the reflection point coordinates are exactly [0  0]. In these cases, the vectorial formula cannot compute the arc cosine.

**Comment by vitorhjr** [comment]
## Geocentric angle antenna - transmitter

Apparently, the vectorial formula used to compute the geocentric angle between antenna and specular point is not applicable to compute the angle antenna transmitter.  The results produced are too much different from the results of https://github.com/vitorhjr/geo-alhazen/blob/main/geo-alhazen-aux/get_geocentric_angle.m#L48.

I think the geometric setup between antenna and transmitter doesn't allow to reuse the vectorial formula of the angle antenna-spec. point.

**Comment by vitorhjr** [comment]
You can run the [demo1_geo_ang](https://github.com/vitorhjr/geo-alhazen/blob/main/demo/demo1_geo_ang.m) to attest the [get_geocentric_angle_vec](https://github.com/vitorhjr/geo-alhazen/blob/main/geo-alhazen-aux/get_geocentric_angle_vec.m) my conclusions.

**Comment by fgnievinski** [comment]
@vitorhjr the input position vector coordinates should be in the geocentric frame, not the local frame.

that way, it should work for the transmitter, too.

also, it should be geo_ang = acosd(temp);

**Comment by vitorhjr** [comment]
You're correct. I carried out wrong the tests with quasigeocentric coordinates. Now I'm getting coordinates as:
```
[~, g, ~, ~, X_spec, Y_spec, X_trans, Y_trans] = get_reflection_spherical(e_grid, Ha_grid, [], [], [], [], 'quasigeo');
pos_ant (2,:) = Rs+Ha_dom;
```
In this case, the code `geo_ang = (acosd(temp))`  works very well
![image](https://user-images.githubusercontent.com/89110447/211566592-075d4217-91ed-4786-bc33-d050bfc28d05.png)

I'm going to update this in the repository.

**Comment by vitorhjr** [comment]
I updated [get_geocentric_angle_vec.m](https://github.com/vitorhjr/geo-alhazen/blob/main/geo-alhazen-aux/get_geocentric_angle_vec.m). I add the word "geocentric" in the commentaries to alert the user and modified the geo angle to `geo_ang = acosd(temp);`.

**Comment by vitorhjr** [comment]
On the other hand, the code still not working for the geo angle between antenna and transmitter.

**Comment by fgnievinski** [comment]
how far off is the geocentric angle between antenna and transmitter -- could it be just 360-geo_ang?

**Comment by vitorhjr** [comment]
> On the other hand, the code still not working for the geo angle between the antenna and transmitter.

I found the problem of why the closed-form and vectorial were not matching. The closed form has been computed to retrieve a radian angle as `geo_ang_at=acos((D.^2 -(Ra).^2 -(Rt).^2)./(-2*(Ra).*(Rt)));`. 

Because of this, when I was comparing it with the vectorial - which retrieves an angle in degrees - the differences were big.

**Comment by vitorhjr** [comment]
Although [get_geocentric_angle](https://github.com/ufrgs-gnss-lab/geo-alhazen/blob/main/geo-alhazen-aux/get_geocentric_angle.m) is computing correctly the two geocentric angles, the geo angle between antenna and transmitter is retrieved in radians while the angle between antenna and specular point is retrieved in degrees.

It could be corrected after splitting the two geo angles in https://github.com/ufrgs-gnss-lab/geo-alhazen/issues/25

**Comment by vitorhjr** [comment]
Finally, vectorial and closed-form geocentric angles showed a good agreement, especially the geo angle between antenna and specular point.
![geoang_as](https://github.com/ufrgs-gnss-lab/geo-alhazen/assets/89110447/66321080-0517-4298-b25e-d334427de866)
![geoang_at](https://github.com/ufrgs-gnss-lab/geo-alhazen/assets/89110447/c8d073b4-6d47-455a-82cc-8c629012961a)

**Comment by vitorhjr** [comment]
Something I find interesting is that discrepancies in the geocentric angle antenna-transmitter show almost same values and the same behavior for all heights, even if I simulate a height of 10 m or 1000 m. So, I think these discrepancies could be corrected by fitting a polynomial.

![geoang_at](https://github.com/ufrgs-gnss-lab/geo-alhazen/assets/89110447/6905f709-848d-4749-89c2-b86a4bc52885)

**Comment by vitorhjr** [comment]
So, vectorial geocentric angle computation is working well.
